### ISSUE TITLE
Plugin installation error

### ISSUE THREAD

**Issue by FishOfPrey** [afawcett/dependencies-cli#12]
When trying to link the plugin to sfdx I got the following error.

> D:\Development\dependencies-cli>sfdx plugins:link .
Installing dependencies for D:\Development\dependencies-cli... !
 !    yarn --non-interactive --mutex=file:C:\Users\[username]\AppData\Local\sfdx\yarn
 !    --cache-folder=C:\Users\[username]\AppData\Local\sfdx\yarn exited with code 1
 !    warning @salesforce/command > @salesforce/core > jsforce > coffee-script@1.12.7: CoffeeScript on NPM has moved to
 !    "coffeescript" (no hyphen)
 !    'yarn' is not recognized as an internal or external command,
 !    operable program or batch file.
 !    error Command failed with exit code 1.
 !

This was with SFDX 6.22.1-022a4908f1.
Is this likely to be related to the plugin, or the CLI itself?

**Comment by FishOfPrey** [comment]
I think I'm getting closer. 

- I manually removed the existing lib directory and ran the typescript compiler (after installing that).
- Installed oclif-dev
- Updated node.js to 8.0
- Manually ran `oclif-dev manifest`, which created `\dependencies-cli\.oclif.manifest.json`

`sfdx plugins` now lists it as a valid plugin.

**Comment by afawcett** [comment]
Thanks @FishOfPrey. I think @jkalloor0701 has registered this plug-in via npm so sfdx plugin install should work without having to build this locally. However i imagine you are doing some fine dev work here so perhaps the result of your efforts needs to be captured in the readme in a developers code section, thoughts?

**Comment by FishOfPrey** [comment]
Yeah, I'm mostly experimenting with changing the toDotFormat() method. So I need to run the typescript compiler to get my changes going.

Generally, I found manually performing the steps in package.json > scripts > prepare and then replacing the actual value with an empty string got my local builds going.

**Comment by afawcett** [comment]
Thanks for sharing @FishOfPrey

**Comment by afawcett** [comment]
Please see here > https://github.com/forcedotcom/dependencies-cli
