### ISSUE TITLE
Error when running the plugin: sObject type 'MetadataComponentDependency' is not supported

### ISSUE THREAD

**Issue by paulroberttaylor** [afawcett/dependencies-cli#20]
CLI Version: sfdx-cli/6.34.0-6fec0d751a (windows-x64) node-v8.9.4

**Comment by leehildebrand** [comment]
@paulroberttaylor I had the same error. The [MetadataComponentDependency documentation](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_metadatacomponentdependency.htm) currently shows the object is in Pilot. Were you able to confirm this was causing your error, and, if so, were you able to enter the pilot?

**Comment by McCheeseJava** [comment]
anyone know what's causing this error?
sObject type 'MetadataComponentDependency' is not supported.

**Comment by leehildebrand** [comment]
@McCheeseJava, I had the same error and eventually figured out that since the dependency API is still pilot, this app only works in orga that have opted into the pilot and have these objects in their org. Most orgs have not opted into the pilot. The pilot is closed. Right now, I have a reminder set to review each set of new release notes to see if these objects have been released as GA and placed into orgs that weren’t in the pilot.

**Comment by leehildebrand** [comment]
@McCheeseJava following up on this: Spring 19 does not reference any additional availability of MetadataCompentDependency in non-pilot orgs, and the [documentation still shows the object as pilot](https://developer.salesforce.com/docs/atlas.en-us.214.0.api_tooling.meta/api_tooling/tooling_api_objects_metadatacomponentdependency.htm). Fingers crossed for Summer 19.

**Comment by snehalp29** [comment]
so now we can't opt in to the pilot ?

**Comment by leehildebrand** [comment]
The response I got was that the pilot was full. At this point, my plan is to check each release notes and hope it moves to Beta.

**Comment by mhgoldfarb** [comment]
Seems to only work for fields on standard objects for both standard and custom fields but does not work on custom objects for both standard and custom fields. It's in beta now and you can provide feedback here (which if you stumble upon this please do): https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A00000020Vu

**Comment by ChuckJonas** [comment]
@afawcett this is well out of pilot, but still seeing this error (not related to your plugin, but just in general when hitting the bulk api).  Seem like sometimes it works, sometimes it doesn't...
