### ISSUE TITLE
SFDX does recognize command.

### ISSUE THREAD

**Issue by adesotamn** [afawcett/dependencies-cli#30]
Getting the following command:

Warning: dependency:components:report is not a sfdx command.

Update SFDX and still go the same error.

**Comment by hkache** [comment]
@adesotamn can you try `sfdx dependency:component:report --help` please. We renamed `component` but apparently forgot to update the README. Sorry about that ... will fix it. Let me know if the new syntax works please.

**Comment by ag** [comment]
@hkache the command you suggested provided me with this error message  `›   Error: command dependency:component:report not found`

I need to display the dependencies. Do you have a workaround or know a different approach?

**Comment by dhbahr** [comment]
It is also happening to me, sfdx complains that `dependency` is not an sfdx command. If I run `sfdx plugins` the `dependencies-cli 1.0.3` does show up.

**Comment by afawcett** [comment]
Please use this version of the plugin > https://github.com/forcedotcom/dependencies-cli
